const text = [
    `Jelly sweet roll jelly beans biscuit pie macaroon chocolate donut. Carrot cake caramels pie sweet apple pie tiramisu carrot cake. Marzipan marshmallow croissant tootsie roll lollipop. Cupcake lemon drops bear claw gummies. Jelly bear claw gummi bears lollipop cotton candy gummi bears chocolate bar cake cookie. Cupcake muffin danish muffin cookie gummies. Jelly beans tiramisu pudding. Toffee soufflé chocolate cake pastry brownie. Oat cake halvah sweet roll cotton candy croissant lollipop. Macaroon tiramisu chocolate bar candy candy carrot cake jelly sweet. Gummies croissant macaroon dessert. Chocolate cake dragée pie.`,
    `Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla eu nulla neque. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla fringilla, justo vel fringilla efficitur, lectus purus interdum orci, in hendrerit tellus sapien ac mi. Pellentesque eget sem orci. Pellentesque imperdiet porta urna nec dapibus. Etiam at finibus turpis. Sed eu interdum mi, euismod imperdiet erat. Nam in orci dapibus diam vestibulum euismod sit amet at diam. Interdum et malesuada fames ac ante ipsum primis in faucibus. Phasellus sodales dui eget lacus volutpat ultricies. Aliquam bibendum leo leo, et ullamcorper quam condimentum eget.`,
    `Donec consequat velit posuere, aliquet sapien id, vehicula turpis. Suspendisse quis nisl eu felis vulputate dictum. Vivamus dignissim, ex sit amet lacinia bibendum, quam lacus congue justo, non volutpat neque dolor non velit. Pellentesque eget finibus diam, id maximus neque. Suspendisse faucibus eros eu enim semper, id convallis tortor consectetur. Aliquam quis magna eget orci dignissim suscipit vitae vitae nunc. Etiam condimentum massa ut sem luctus maximus eget vitae massa. Nunc at erat quis dui facilisis ultricies.`,
    `In hac habitasse platea dictumst. Vestibulum lobortis metus tellus, non scelerisque lectus rhoncus a. Aliquam mattis nisi non lacus interdum, sed euismod eros consequat. Nulla maximus tortor id elementum accumsan. Maecenas tincidunt at nulla mollis ullamcorper. Vivamus non egestas nulla. Nullam vel turpis ac lacus mattis lacinia tincidunt eu enim. Maecenas at diam eu lacus bibendum aliquet. Integer bibendum magna nec vestibulum blandit. Sed sed tortor mi.`,
    `Vivamus vel accumsan sapien. Mauris bibendum euismod libero, sit amet dictum tellus iaculis at. Maecenas eu sem sed risus efficitur ultricies dapibus non leo. Integer ultrices, dolor vitae rhoncus laoreet, orci sapien accumsan erat, ultrices blandit urna dui eu elit. Pellentesque mi nunc, feugiat ut venenatis vel, hendrerit sed sem. Integer ultricies ex aliquam dapibus faucibus. Sed enim libero, cursus eu turpis id, consequat aliquam leo.`,
    `Integer tincidunt purus varius, commodo sapien in, pretium lacus. Suspendisse potenti. Sed id enim fermentum, venenatis leo nec, finibus nisl. Praesent pretium et ex vitae volutpat. Curabitur sed augue pulvinar, pharetra neque vel, finibus ligula. Pellentesque vitae justo enim. Proin sit amet est vel erat facilisis consequat. Pellentesque sit amet scelerisque purus, quis maximus diam. Suspendisse quis egestas leo. Nam porta urna mi, a lobortis dolor convallis nec.`,
    `Cras pharetra libero in nisi viverra tincidunt. Nulla turpis sapien, tristique eu tristique vitae, bibendum et massa. Cras nibh libero, laoreet eget rutrum tempus, ullamcorper at arcu. Donec id massa lorem. Aenean lorem nunc, posuere imperdiet molestie eget, pretium et nisi. Sed consequat libero sed sem hendrerit, lacinia commodo leo mollis. Proin hendrerit, urna in pretium posuere, lectus orci placerat ligula, vitae ullamcorper dolor arcu eu velit. Vivamus gravida scelerisque dui in pulvinar. Sed volutpat in turpis in malesuada. Nunc sagittis turpis odio, egestas sagittis tellus bibendum quis. Suspendisse condimentum laoreet urna quis ornare. Nunc eu orci tempor, ullamcorper arcu sed, egestas massa. Sed sollicitudin id nisl vitae aliquet. Ut non aliquam arcu. Vivamus consectetur magna vulputate, tincidunt sapien sed, facilisis felis.`,
    `Mauris et magna massa. Aenean interdum, ante a gravida vestibulum, nunc urna gravida odio, in suscipit nunc felis a dolor. Mauris finibus mi a ipsum elementum lobortis. Quisque at dolor eu tellus vulputate placerat eu vel augue. Aenean ut lacus blandit, tristique risus ut, placerat metus. Quisque condimentum, dolor vel efficitur eleifend, est neque ultrices nunc, sit amet tempor enim odio nec quam. Phasellus rhoncus, tellus ac auctor mollis, sem magna aliquam nulla, non accumsan urna magna in purus.`,
    `Next level tbh everyday carry, blog copper mug forage kitsch roof party pickled hammock kale chips tofu. Etsy shoreditch 8-bit microdosing, XOXO viral butcher banh mi humblebrag listicle woke bicycle rights brunch before they sold out ramps. Twee shabby chic taiyaki flannel, enamel pin venmo vape four loko. Hexagon kale chips typewriter kitsch 8-bit organic plaid small batch keffiyeh ethical banh mi narwhal echo park cronut.`,
    `Zombie ipsum reversus ab viral inferno, nam rick grimes malum cerebro. De carne lumbering animata corpora quaeritis. Summus brains sit​​, morbo vel maleficia? De apocalypsi gorger omero undead survivor dictum mauris. Hi mindless mortuis soulless creaturas, imo evil stalking monstra adventus resi dentevil vultus comedat cerebella viventium. Qui animated corpse, cricket bat max brucks terribilem incessu zomby. The voodoo sacerdos flesh eater, suscitat mortuos comedere carnem virus. Zonbi tattered for solum oculi eorum defunctis go lum cerebro. Nescio brains an Undead zombies. Sicut malus putrid voodoo horror. Nigh tofth eliv ingdead.`,
    `Cat gets stuck in tree firefighters try to get cat down firefighters get stuck in tree cat eats firefighters' slippers kitty power ignore the squirrels, you'll never catch them anyway for what a cat-ass-trophy! or purr as loud as possible, be the most annoying cat that you can, and, knock everything off the table. Pretend you want to go out but then don't bite off human's toes, yet disappear for four days and return home with an expensive injury; bite the vet so catch eat throw up catch eat throw up bad birds. `,
    `This opera's as lousy as it is brilliant! Your lyrics lack subtlety. You can't just have your characters announce how they feel. That makes me feel angry! Anyhoo, your net-suits will allow you to experience Fry's worm infested bowels as if you were actually wriggling through them.
  I just told you! You've killed me! Fry! Quit doing the right thing, you jerk! Michelle, I don't regret this, but I both rue and lament it. Morbo can't understand his teleprompter because he forgot how you say that letter that's shaped like a man wearing a hat.`,
    `Airedale hard cheese mozzarella. Pecorino melted cheese port-salut emmental babybel cheese and wine melted cheese manchego. Everyone loves blue castello everyone loves fromage cheese slices airedale cheddar cream cheese. Bavarian bergkase who moved my cheese halloumi port-salut gouda jarlsberg ricotta rubber cheese. Stinking bishop smelly cheese brie.`,
    `Salvia glossier subway tile, leggings mustache YOLO semiotics chia. Pitchfork tbh af blog church-key meggings vaporware PBR&B master cleanse post-ironic man bun pabst mustache letterpress synth. Snackwave raw denim godard, 3 wolf moon shaman offal kitsch unicorn live-edge selvage schlitz fashion axe vaporware drinking vinegar prism. Shabby chic tacos artisan, chambray chicharrones cardigan leggings typewriter af pop-up williamsburg meditation PBR&B viral. You probably haven't heard of them DIY jean shorts subway tile fashion axe bushwick kitsch tumeric cloud bread vaporware freegan franzen pork belly chicharrones banh mi.`,
    `Man braid celiac synth freegan readymade, pitchfork fam salvia waistcoat lomo bitters gentrify four loko. Pitchfork semiotics post-ironic vegan. Tofu meditation microdosing hashtag semiotics venmo. Flexitarian vape tilde taiyaki. Prism poutine farm-to-table, messenger bag vegan taxidermy tattooed sartorial squid jean shorts fixie selvage trust fund vape.`,
    `Rutters Plate Fleet boom chandler Brethren of the Coast handsomely lookout marooned brigantine knave. Buccaneer gangway jack rum loot spyglass line Jack Tar fore gaff. Gaff topmast scuttle ballast swab draught measured fer yer chains dance the hempen jig Chain Shot yardarm.`,
  ];
  export default text;